#!/bin/bash
set -e

# Establish source dir for relative includes
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

# Pre-suite (download and extract requested release)
# shellcheck source=../shared/entrypoint-pre disable=SC1091
. "$DIR/../shared/entrypoint-pre"

# Make sure required Anubis env vars are set
# shellcheck source=../shared/entrypoint-anubis-pre disable=SC1091
. "$DIR/../shared/entrypoint-anubis-pre"

# TODO: consolidate the output generation and error handling into a shared script for use across all evaluations.
eval $(pdk env)

# Run parser and emit output to json document
{
  puppet parser validate --render-as json manifests > parser_output.json
  exit_code=$?
} || {
  true
}

# Ensure file contains valid JSON if there's no output
if [[ ! -s parser_output.json ]]; then
  echo 'null' > parser_output.json
fi
ruby -e "require 'json'; puts ({ exit_code: $exit_code, output: JSON.parse(File.read('parser_output.json')) }).to_json" > anubis_output.json
cat anubis_output.json

# Post results back to given API endpoint
# shellcheck source=../shared/entrypoint-anubis-post disable=SC1091
. "$DIR/../shared/entrypoint-anubis-post"

# shellcheck source=shared/entrypoint-post disable=SC1091
. "$DIR/../shared/entrypoint-post"

exit 0

